#!/bin/sh

# OpenWRT hotplug script to be placed in /etc/hotplug.d/usb

BINARY="/usr/bin/fusee-nano /usr/share/fusee-nano/payload.bin"
APX_PRODID="955/7321/102"

if [ "${ACTION}" = "add" ]; then
	if [ "${PRODUCT}" = "${APX_PRODID}" ]; then
		${BINARY}
		echo 0 > /sys/class/leds/a5-v11\:red\:power/brightness
		for i in {1..4}; do
			echo -n $(($i%2)) > /sys/class/leds/a5-v11\:blue\:system/brightness
			sleep 1
		done
		echo 255 > /sys/class/leds/a5-v11\:red\:power/brightness
	else
		sleep 3
		for i in $(ls /dev/sd*); do
			umount /mnt
			mount $i /mnt/
			if [ -f /mnt/payload.bin ]; then
				echo 0 > /sys/class/leds/a5-v11\:red\:power/brightness
				cp -f /mnt/payload.bin /usr/share/fusee-nano/
				umount /mnt
				for i in {1..4}; do
					echo -n $(($i%2)) > /sys/class/leds/a5-v11\:blue\:system/brightness
					sleep 1
				done
				echo 255 > /sys/class/leds/a5-v11\:red\:power/brightness
				break
			fi
		done
	fi
fi
